<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Room Earnings Report</title>
    <style>
        /* UPDATE: Added 'DejaVu Sans' to support Peso sign */
        body { 
            font-family: 'DejaVu Sans', sans-serif; 
            font-size: 10px; 
            color: #333; 
        }
        
        .header { border-bottom: 2px solid #2563eb; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { color: #1e40af; margin: 0; font-size: 18px; }
        .meta { text-align: right; font-size: 9px; color: #666; }
        
        .summary-box { background: #f3f4f6; padding: 10px; border: 1px solid #ddd; margin-bottom: 20px; }
        .summary-table { width: 100%; text-align: center; }
        .stat-label { font-size: 8px; text-transform: uppercase; color: #666; }
        .stat-val { font-size: 14px; font-weight: bold; color: #333; }
        
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #2563eb; color: white; padding: 6px; text-align: left; }
        td { border-bottom: 1px solid #eee; padding: 6px; }
        .text-right { text-align: right; }
        
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 8px; color: #999; border-top: 1px solid #eee; padding-top: 5px; }
    </style>
</head>
<body>
    <div class="header">
        <table width="100%">
            <tr>
                <td><h1>ROOM EARNINGS REPORT</h1></td>
                <td class="meta">
                    Generated: {{ $generatedAt->format('M d, Y H:i') }}<br>
                    Filter: {{ $filter }}
                </td>
            </tr>
        </table>
    </div>

    <div class="summary-box">
        <table class="summary-table">
            <tr>
                <td>
                    <div class="stat-label">Total Revenue</div>
                    <div class="stat-val" style="color: #059669">₱{{ number_format($data['totalEarnings'], 2) }}</div>
                </td>
                <td>
                    <div class="stat-label">Total Bookings</div>
                    <div class="stat-val">{{ $data['totalBookings'] }}</div>
                </td>
                <td>
                    <div class="stat-label">Refunds</div>
                    <div class="stat-val" style="color: #dc2626">₱{{ number_format($data['totalRefunds'], 2) }}</div>
                </td>
                <td>
                    <div class="stat-label">Best Category</div>
                    <div class="stat-val" style="color: #2563eb">{{ $data['topCategory'] }}</div>
                </td>
            </tr>
        </table>
    </div>

    <div style="font-weight: bold; margin-bottom: 5px; color: #444;">DETAILED ROOM BREAKDOWN</div>
    <table>
        <thead>
            <tr>
                <th width="30%">Room Name</th>
                <th width="15%">Category</th>
                <th width="10%" class="text-right">Bookings</th>
                <th width="10%" class="text-right">Occ %</th>
                <th width="15%" class="text-right">Avg Rate</th>
                <th width="20%" class="text-right">Net Earnings</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['rows'] as $row)
                <tr>
                    <td>{{ $row['name'] }}</td>
                    <td>{{ $row['category'] }}</td>
                    <td class="text-right">{{ $row['bookings'] }}</td>
                    <td class="text-right">{{ $row['occupancy'] }}%</td>
                    <td class="text-right">₱{{ number_format($row['adr'], 2) }}</td>
                    <td class="text-right font-bold">₱{{ number_format($row['earnings'], 2) }}</td>
                </tr>
            @endforeach
            <tr style="background: #f0f0f0; font-weight: bold;">
                <td colspan="5">TOTAL</td>
                <td class="text-right">₱{{ number_format($data['totalEarnings'], 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        Confidential Report - Generated by System
    </div>
</body>
</html>